Script started on 2016年03月14日 星期一 10:07:56
]0;zrh@ubuntu: ~[01;32mzrh@ubuntu[00m:[01;34m~[00m$ g++ cpp[K[K[Klab1.cpp -o lab1
]0;zrh@ubuntu: ~[01;32mzrh@ubuntu[00m:[01;34m~[00m$ ./lab1
Input N
22
11 34 17 52 26 13 40 20 10 5 16 8 4 2 1 ]0;zrh@ubuntu: ~[01;32mzrh@ubuntu[00m:[01;34m~[00m$ ls[K[Ksl[K[Kls[K[Kls[K[Kls[K[Kexit

Script done on 2016年03月14日 星期一 10:08:55
